name: Build all

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build-wasm:
    name: Build Wasm
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: make sr9.wasm
      - uses: actions/upload-artifact@v4
        with:
          name: wasm
          path: sr9.wasm
  build:
    name: Build
    needs: build-wasm
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: wasm
      - uses: actions/upload-pages-artifact@v3
  deploy:
    name: Deploy
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
