name: Build all

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build-sqlite:
    name: Build SQLite
    runs-on: ubuntu-latest
    steps:
      - name: Cache SQLite source
        id: cache-sqlite-source
        uses: actions/cache@v4
        with:
          path: sqlite-amalgamation-3420000.zip
          key: sqlite-3420000-source
      - name: Download SQLite source
        if: steps.cache-sqlite-source.outputs.cache-hit != 'true'
        run: |
          wget https://www.sqlite.org/2023/sqlite-amalgamation-3420000.zip
      - name: Cache SQLite build
        id: cache-sqlite-build
        uses: actions/cache@v4
        with:
          path: |
            sqlite-amalgamation-3420000/libsqlite3.a
            sqlite-amalgamation-3420000/sqlite3.h
          key: sqlite-3420000-build-${{ runner.os }}-emcc
      - name: Install build dependencies
        if: steps.cache-sqlite-build.outputs.cache-hit != 'true'
        run: |
          sudo apt-get -qq update && sudo apt-get --quiet --assume-yes install \
            emscripten build-essential
      - name: Build SQLite
        if: steps.cache-sqlite-build.outputs.cache-hit != 'true'
        run: |
          unzip sqlite-amalgamation-3420000.zip
          cd sqlite-amalgamation-3420000
          emcc -Os -c sqlite3.c -o sqlite3.o
          emar rcs libsqlite3.a sqlite3.o
      - uses: actions/upload-artifact@v4
        with:
          name: sqlite3
          path: |
            sqlite-amalgamation-3420000/libsqlite3.a
            sqlite-amalgamation-3420000/sqlite3.h

  build-libtiff:
    name: Build libtiff
    runs-on: ubuntu-latest
    steps:
      - name: Cache libtiff source
        id: cache-libtiff-source
        uses: actions/cache@v4
        with:
          path: tiff-4.5.1.tar.gz
          key: libtiff-4.5.1-source
      - name: Download libtiff source
        if: steps.cache-libtiff-source.outputs.cache-hit != 'true'
        run: |
          wget https://download.osgeo.org/libtiff/tiff-4.5.1.tar.gz
      - name: Cache libtiff build
        id: cache-libtiff-build
        uses: actions/cache@v4
        with:
          path: |
            tiff-4.5.1/libtiff/libtiff.a
            tiff-4.5.1/libtiff/tiffio.h
            tiff-4.5.1/libtiff/tiff.h
            tiff-4.5.1/libtiff/tiffvers.h
          key: libtiff-4.5.1-build-${{ runner.os }}-emcc
      - name: Install build dependencies
        if: steps.cache-libtiff-build.outputs.cache-hit != 'true'
        run: |
          sudo apt-get -qq update && sudo apt-get --quiet --assume-yes install \
            emscripten build-essential cmake
      - name: Build libtiff
        if: steps.cache-libtiff-build.outputs.cache-hit != 'true'
        run: |
          tar -xzf tiff-4.5.1.tar.gz
          cd tiff-4.5.1
          # Remove build directory if it exists from previous partial runs
          rm -rf build
          mkdir build
          cd build
          emcmake cmake .. \
            -DBUILD_SHARED_LIBS=OFF \
            -Dzlib=OFF \
            -Dpixarlog=OFF \
            -Djpeg=OFF \
            -Dold-jpeg=OFF \
            -Djbig=OFF \
            -Dlzma=OFF \
            -Dzstd=OFF \
            -Dwebp=OFF \
            -Dcxx=OFF \
            -DCMAKE_INSTALL_PREFIX=$(pwd)/install
          emmake make -j$(nproc)
          # Copy built library to expected location
          cp libtiff/libtiff.a ../libtiff/
      - uses: actions/upload-artifact@v4
        with:
          name: libtiff
          path: |
            tiff-4.5.1/libtiff/libtiff.a
            tiff-4.5.1/libtiff/tiffio.h
            tiff-4.5.1/libtiff/tiff.h
            tiff-4.5.1/libtiff/tiffvers.h
  build-proj:
    name: Build PROJ
    runs-on: ubuntu-latest
    needs: [build-sqlite, build-libtiff]
    steps:
      - uses: actions/checkout@v5
        with:
          repository: OSGeo/PROJ
          ref: 9.6.2
      - uses: actions/download-artifact@v4
        with:
          name: sqlite3
          path: ./sqlite3/
      - uses: actions/download-artifact@v4
        with:
          name: libtiff
          path: ./libtiff/
      - name: Cache PROJ build
        id: cache-proj-build
        uses: actions/cache@v4
        with:
          path: |
            build/install/lib/libproj.a
            build/install/include
          key: proj-9.6.2-build-${{ runner.os }}-emcc-libtiff451-${{ hashFiles('sqlite3/libsqlite3.a', 'libtiff/libtiff.a') }}
      - name: Install build dependencies
        if: steps.cache-proj-build.outputs.cache-hit != 'true'
        run: |
          sudo apt-get -qq update && sudo apt-get --quiet --assume-yes install \
            emscripten build-essential cmake
      - name: Build PROJ
        if: steps.cache-proj-build.outputs.cache-hit != 'true'
        run: |
          # Remove build directory if it exists from previous partial runs
          rm -rf build
          mkdir build
          cd build
          emcmake cmake .. \
            -DBUILD_APPS=OFF \
            -DBUILD_TESTING=OFF \
            -DBUILD_SHARED_LIBS=OFF \
            -DSQLite3_INCLUDE_DIR=$(pwd)/../sqlite3 \
            -DSQLite3_LIBRARY=$(pwd)/../sqlite3/libsqlite3.a \
            -DENABLE_CURL=OFF \
            -DENABLE_TIFF=ON \
            -DTIFF_INCLUDE_DIR=$(pwd)/../libtiff \
            -DTIFF_LIBRARY=$(pwd)/../libtiff/libtiff.a \
            -DCMAKE_INSTALL_PREFIX=$(pwd)/install
          emmake make -j$(nproc)
          emmake make install
      - name: Stage artifacts
        run: |
          # Copy files to expected artifact structure
          mkdir -p artifact-staging
          cp build/install/lib/libproj.a artifact-staging/
          cp -r build/install/include artifact-staging/
          # Include SQLite3 library that PROJ depends on
          cp sqlite3/libsqlite3.a artifact-staging/
          # Include libtiff library that PROJ depends on
          cp libtiff/libtiff.a artifact-staging/
      - uses: actions/upload-artifact@v4
        with:
          name: proj
          path: artifact-staging/
  build-wasm:
    name: Build Wasm
    runs-on: ubuntu-24.04
    needs: build-proj
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v4
        with:
          name: proj
          path: ./
      - name: Install build dependencies
        run: |
          sudo apt-get -qq update && sudo apt-get --quiet --assume-yes install \
            emscripten build-essential
      - run: |
          echo "=== Checking downloaded artifacts ==="
          ls -la
          echo "=== Creating build structure ==="
          # Create build directory and move artifacts to expected locations
          mkdir -p build/include
          # Move libproj.a to expected location
          if [ -f libproj.a ]; then
            mv libproj.a build/
            echo "Moved libproj.a to build/"
          else
            echo "ERROR: libproj.a not found"
            exit 1
          fi
          # Move libsqlite3.a to expected location
          if [ -f libsqlite3.a ]; then
            mv libsqlite3.a build/
            echo "Moved libsqlite3.a to build/"
          else
            echo "ERROR: libsqlite3.a not found"
            exit 1
          fi
          # Move libtiff.a to expected location
          if [ -f libtiff.a ]; then
            mv libtiff.a build/
            echo "Moved libtiff.a to build/"
          else
            echo "ERROR: libtiff.a not found"
            exit 1
          fi
          # Move headers to expected location
          if [ -d include ]; then
            mv include/* build/include/
            echo "Moved headers to build/include/"
          else
            echo "ERROR: include directory not found"
            exit 1
          fi
          echo "=== Final build structure ==="
          ls -la build/
          ls -la build/include/
          echo "=== Building WASM ==="
          make sr9.wasm
      - uses: actions/upload-artifact@v4
        with:
          name: wasm
          path: |
            sr9.wasm
            sr9.js
  build:
    name: Build
    runs-on: ubuntu-24.04
    needs: build-wasm
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Cache TypeScript
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-typescript-global
          restore-keys: |
            ${{ runner.os }}-typescript-
      - run: npm install -g typescript
      - uses: actions/download-artifact@v4
        with:
          name: wasm
          path: ./
      - run: |
          echo "=== Checking downloaded WASM artifacts ==="
          ls -la
          echo "=== Building TypeScript ==="
          make script.js
          echo "=== Copying WASM files to _site ==="
          cp sr9.wasm _site/
          cp sr9.js _site/
          echo "=== Final _site contents ==="
          ls -la _site/
          echo "=== Adding additional files ==="
          echo "${{ vars.adstxt }}" > _site/ads.txt
          curl -o _site/pico.min.css https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css
          echo "=== Final _site contents ==="
          ls -la _site/
      - uses: actions/upload-pages-artifact@v4
  deploy:
    name: Deploy
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
