name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  build-wasm:
    name: 'Build WASM'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
