name: Build all

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build-wasm:
    name: Build Wasm
    runs-on: ubuntu-24.04
    continue-on-error: true
    steps:
      - run: |
          sudo apt-get -qq update
          sudo apt-get --quiet --assume-yes install emscripten libsqlite3-dev
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: OSGeo/PROJ
          ref: 9.6.2
          path: libs/proj
      - name: Patch PROJ CMake to skip SQLite3 for WASM
        run: |
          find libs/proj -name CMakeLists.txt -exec sed -i 's/find_package(SQLite3 REQUIRED)/#find_package(SQLite3 REQUIRED)/g' {} +
      - name: Aggressively patch PROJ CMake to skip SQLite3 and TIFF for WASM
        run: |
          find libs/proj -name CMakeLists.txt -exec sed -i '/SQLite3/s/^/#/' {} +
          find libs/proj -name CMakeLists.txt -exec sed -i '/TIFF/s/^/#/' {} +
      - run: |
          cd libs/proj
          mkdir build && cd build
          emcmake cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/proj-install -DENABLE_SQLITE=OFF -DPROJ_DATABASE=OFF -DPROJ_NETWORK=OFF -DBUILD_PROJ_DATABASE=OFF -DBUILD_SHARED_LIBS=OFF
          emmake make
          emmake make install
      - run: |
          make sr9.wasm
      - uses: actions/upload-artifact@v4
        with:
          name: wasm
          path: |
            sr9.wasm
            sr9.js
  build:
    name: Build
    runs-on: ubuntu-24.04
    continue-on-error: true
    needs: build-wasm
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: wasm
          path: _site
      - run: |
          make script.js
          echo "${{ vars.adstxt }}" > _site/ads.txt
      - uses: actions/upload-pages-artifact@v3
  deploy:
    name: Deploy
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
